BikeShopv2/Controllers/BikeShopController.cs
using BikeShopv2.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BikeShopv2.Controllers
{
    public class BikeShopController : Controller
    {
        // GET: BikeShop
        BikeShopDataContext data = new BikeShopDataContext();
        // Hàm lấy n sản phẩm mới
        private List<SANPHAM> LaySanPham(int count)
        {
            //Sắp xếp sách theo ngày cập nhật, sau đó lấy top @count 
            return data.SANPHAMs.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        //Phương thức Index: Không có tham số (null) hoặc có tham số là số nguyên (biến page)
        public ActionResult Index(int? page)
        {
            //kích thước trang = số mẫu tin cho 1 trang
            int pagesize = 5;
            //Số thứ tự trang: nêu page là null thì pagenum = 1, ngược lại pagenum = page
            int pagenum = (page ?? 1);
            //Lấy top 5 bán chạy nhất;
            var sp = LaySanPham(15);
            return View(sp.ToPagedList(pagenum, pagesize));
        }
        public ActionResult LoaiSanPham()
        {
            var lsp = from s in data.LOAISANPHAMs select s;
            return PartialView(lsp);
        }

        public ActionResult SanPhamTheoLoai(int id)
        {
            var sptl = from s in data.SANPHAMs where s.ID_LSP == id select s;
            return View(sptl);

        }
        public ActionResult Brand()
        {
            var br = from s in data.BRANDs select s;
            return PartialView(br);
        }
        public ActionResult SanPhamTheoBrand(int id)
        {
            var spbr = from s in data.SANPHAMs where s.ID_BRAND == id select s;
            return View(spbr);

        }
        public ActionResult ChiTietSanPham(int id)
        {
            var sp = from s in data.SANPHAMs where s.ID_SANPHAM == id select s;
            return View(sp.Single());
        }
    }
}

BikeShopv2/Controllers/BrandController.cs
using BikeShopv2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BikeShopv2.Controllers
{
    public class BrandController : Controller
    {
        // GET: Brand
        BikeShopDataContext data = new BikeShopDataContext();
        public ActionResult Index()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View(data.BRANDs.ToList());
        }
        //2. Hiện thi chi tiết 1 loại sản phẩm
        public ActionResult Details(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var lsp = from sp in data.BRANDs where sp.ID_BRAND == id select sp;
                return View(lsp.SingleOrDefault());
            }
        }
        //3. Thêm mới loại sản phẩm
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View();
        }
        [HttpPost]
        public ActionResult Create(BRAND lsp)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                data.BRANDs.InsertOnSubmit(lsp);
                data.SubmitChanges();

                return RedirectToAction("Index", "Brand");
            }
        }
        //4. Xóa 1 loại sản phẩm gồm 2 trang: xác nhận xóa và xử lý xóa
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var lsp = from s in data.BRANDs where s.ID_BRAND == id select s;
                return View(lsp.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Xacnhanxoa(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                BRAND lsp = data.BRANDs.SingleOrDefault(n => n.ID_BRAND == id);
                foreach (var item in data.SANPHAMs)
                {
                    if (item.ID_BRAND == id)
                    {
                        data.SANPHAMs.DeleteOnSubmit(item);
                        data.SubmitChanges();
                    }
                }
                data.BRANDs.DeleteOnSubmit(lsp);
                data.SubmitChanges();

                return RedirectToAction("Index", "Brand");
            }
        }
        //5. Điều chỉnh thông tin 1 loại sản phẩm gồm 2 trang: Xem và điều chỉnh và cập nhật lưu lại
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var lsp = from s in data.BRANDs where s.ID_BRAND == id select s;
                return View(lsp.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Edit")]
        public ActionResult Capnhat(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                BRAND lsp = data.BRANDs.SingleOrDefault(n => n.ID_BRAND == id);

                UpdateModel(lsp);
                data.SubmitChanges();
                return RedirectToAction("Index", "Brand");
            }
        }
    }
}

BikeShopv2/Controllers/LoaiSanPhamController.cs
using BikeShopv2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BikeShopv2.Controllers
{
    public class LoaiSanPhamController : Controller
    {
        // GET: LoaiSanPham
        BikeShopDataContext data = new BikeShopDataContext();
        public ActionResult Index()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View(data.LOAISANPHAMs.ToList());
        }
        //2. Hiện thi chi tiết 1 loại sản phẩm
        public ActionResult Details(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var lsp = from sp in data.LOAISANPHAMs where sp.ID_LSP == id select sp;
                return View(lsp.SingleOrDefault());
            }
        }
        //3. Thêm mới loại sản phẩm
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
                return View();
        }
        [HttpPost]
        public ActionResult Create(LOAISANPHAM lsp)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                data.LOAISANPHAMs.InsertOnSubmit(lsp);
                data.SubmitChanges();

                return RedirectToAction("Index", "LoaiSanPham");
            }
        }
        //4. Xóa 1 loại sản phẩm gồm 2 trang: xác nhận xóa và xử lý xóa
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var lsp = from s in data.LOAISANPHAMs where s.ID_LSP == id select s;
                return View(lsp.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult Xacnhanxoa(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                LOAISANPHAM lsp = data.LOAISANPHAMs.SingleOrDefault(n => n.ID_LSP == id);
                foreach(var item in data.SANPHAMs)
                {
                    if (item.ID_LSP == id)
                    {
                        data.SANPHAMs.DeleteOnSubmit(item);
                        data.SubmitChanges();
                    }
                }
                data.LOAISANPHAMs.DeleteOnSubmit(lsp);
                data.SubmitChanges();

                return RedirectToAction("Index", "LoaiSanPham");
            }
        }
        //5. Điều chỉnh thông tin 1 loại sản phẩm gồm 2 trang: Xem và điều chỉnh và cập nhật lưu lại
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                var lsp = from s in data.LOAISANPHAMs where s.ID_LSP == id select s;
                return View(lsp.SingleOrDefault());
            }
        }
        [HttpPost, ActionName("Edit")]
        public ActionResult Capnhat(int id)
        {
            if (Session["Taikhoanadmin"] == null)
                return RedirectToAction("Login", "Admin");
            else
            {
                LOAISANPHAM lsp = data.LOAISANPHAMs.SingleOrDefault(n => n.ID_LSP == id);

                UpdateModel(lsp);
                data.SubmitChanges();
                return RedirectToAction("Index", "LoaiSanPham");
            }
        }
    }
}

BikeShopv2/Views/BikeShop/Brand.cshtml
<div class="list-group">
    @foreach (var br in Model)
    {
        <a href="@Url.Action("SanPhamTheoBrand", "BikeShop", new { id = br.ID_BRAND })" class="list-group-item"> @br.Brand1</a>
    }
</div>

BikeShopv2/Views/BikeShop/ChiTietSanPham.cshtml
<style type="text/css">
    #Datmua a {
        clear: both;
        background-color: red;
        color: white;
        width: 120px;
        height: 35px;
        display: block;
        float: right;
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
    }

        #Datmua a:hover {
            background-color: gray;
            color: red;
        }
</style>
@{
    ViewBag.Title = "ChiTietSanPham";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3> THÔNG TIN CHI TIẾT SẢN PHẨM</h3>
<div>
    <div style="width:40%; float:left; border-left: dotted 1px; border-color:azure">
        <img src="~/HinhSanPham/@Model.Anh" width="70%" />
    </div>
    <div style="width:60%; float:left; padding:10px">
        <h4 style="font-weight:bold; color:red">Tên sản phẩm: @Model.TenSP </h4>
        <p style="text-align:justify"><Span style="font-weight:bold"> Mô tả: </Span>@Model.MoTa </p>
        <p style="font-weight:bold"> Giá bán: <span style="color:red; font-size:16pt "> @Model.GiaBan VNĐ </span></p>
    </div>
    <div>
        <div id="Datmua">
            <a href="@Url.Action("ThemGioHang", "GioHang", new { id = @Model.ID_SANPHAM , strURL= Request.Url.ToString() })" class="list-group-item">
                ĐẶT MUA
            </a>
        </div>
    </div>
</div>

BikeShopv2/Views/BikeShop/Index.cshtml
@using BikeShopv2.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SANPHAM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SẢN PHẨM MỚI </h2>

<div class="row">
    @foreach (var sp in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("ChiTietSanPham", "BikeShop", new { id = sp.ID_SANPHAM})">
                    <img alt="@sp.TenSP" src="~/HinhSanPham/@sp.Anh" width="200" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @sp.TenSP
                        </h4>
                        <p></p>
                    </div>
                </a>
                <div class="ratings">
                    <p class="pull-right">15 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star">
                        </span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
<div class="col-md-3">
    <p class="lead">LOẠI XE</p>
    @Html.Action("LoaiSanPham", "BikeShop")
    <p class="lead">SẢN PHẨM KHÁC</p>
    @Html.Action("Brand", "BikeShop")
</div>
<div>
    Trang @(Model.PageNumber>Model.PageCount?3:Model.PageNumber) /@Model.PageCount
</div>
<div class="Menutrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    .Menutran li {
        display: inline
    }
</style>

BikeShopv2/Views/BikeShop/LoaiSanPham.cshtml
<div class="list-group">
    @foreach (var lsp in Model)
    {
        <a href="@Url.Action("SanPhamTheoLoai", "BikeShop", new { id = lsp.ID_LSP })" class="list-group-item"> @lsp.TenLoai</a>
    }
</div>

BikeShopv2/Views/BikeShop/SanPhamTheoBrand.cshtml
@{
    ViewBag.Title = "SanPhamTheoBrand";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SẢN PHẨM THEO HÃNG</h2>


<div class="row">
    @foreach (var sp in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("ChiTietSanPham","BikeShop", new { id = sp.ID_SANPHAM})">
                    <img alt="@sp.TenSP" src="~/HinhSanPham/@sp.Anh" width="200" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @sp.TenSP
                        </h4>
                        <p></p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star">
                            </span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
            </div>
        </div>
    }
</div>

BikeShopv2/Views/BikeShop/SanPhamTheoLoai.cshtml
@{
    ViewBag.Title = "SanPhamTheoLoai";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SẢN PHẨM THEO LOẠI</h2>


<div class="row">
    @foreach (var sptl in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("ChiTietSanPham","BikeShop", new { id = sptl.ID_SANPHAM})">
                    <img alt="@sptl.TenSP" src="~/HinhSanPham/@sptl.Anh" width="200" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @sptl.TenSP
                        </h4>
                        <p></p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star">
                            </span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
            </div>
        </div>
    }
</div>